### PR TITLE
Support node 12

### PR DESCRIPTION
**Pull request by caseywebdev**
### Description of the Change

Add node 12 to the build systems

### Benefits

Supports the latest version of node

### CODE REVIEW

**Comment by benjamn** [comment]
Thanks for working on this @caseywebdev! We're planning to switch from `pathwatcher` to `@atom/watcher` for [Meteor 1.9](https://github.com/meteor/meteor/pull/10527), and Node.js 12 compatibility is the only blocker.

**Comment by smashwilson** [comment]
Just so you're aware: CircleCI is currently failing because the version of `clang-tidy` on homebrew changed and inherited additional checks. So if you see that failing, it's not you 😅

**Comment by nathansobo** [comment]
Hey @benjamn, just a heads-up: Atom has been hitting some crashes on Windows CI that seem to be originating from `@atom/watcher`. I'm currently exploring a transition to yet *another* solution which spawns a Rust subprocess based on the [`notify` crate](https://docs.rs/notify/4.0.10/notify/) to do the watching and relays it to JS. This will live in the [`@atom/notify` module](https://github.com/atom/notify).

It's still a bit early, but if I'm successful with this approach, we may not end up using `watcher` in Atom. I just wanted to let you know in case that influences your decision to depend on this module.

@smashwilson Feel free to chime in.

**Comment by smashwilson** [comment]
@caseywebdev on a related note, would you be interested in having push and merge rights on this repo and the npm package? That way you wouldn't have to be blocked on me :smile:

**Comment by caseywebdev** [comment]
I can't really commit time to maintaining it, so I'd have to respectfully decline. I can't even get this PR to pass 😉

**Comment by taratatach** [comment]
Hey @smashwilson, are you planning on working on this PR and merging it anytime soon? It's not possible to compile @atom/watcher on macOS with Electron 6 because of the `nan` version used in the latest release.
If I can help in any way, please let me know.

**Comment by smashwilson** [comment]
I haven't been actively working on this module for some time, no.

If you're so inclined, though, you could start with this PR and get the builds green and I'd be happy to merge :smile:

**Comment by DeeDeeG** [comment]
For anyone reading this, Node 12 support appears to have landed with #234.

**Pull request closed without merging**
