### PR TITLE
Add Probot no-response configuration

### PR DESCRIPTION
**Pull request by jasonrudolph**
### Description of the Change

Please see https://github.com/atom/atom/pull/18077

### Benefits

Please see https://github.com/atom/atom/pull/18077

### Possible Drawbacks

Please see https://github.com/atom/atom/pull/18077

### CODE REVIEW

**Comment by jasonrudolph** [comment]
@smashwilson: This change is failing on Circle CI. Should Circle CI be passing? (I ask because I'm not sure if atom/watcher migrated from Circle CI 1.0 to 2.0 before 1.0 went EOL.)

**Comment by jasonrudolph** [comment]
> This change is failing on Circle CI. Should Circle CI be passing? (I ask because I'm not sure if atom/watcher migrated from Circle CI 1.0 to 2.0 before 1.0 went EOL.)

I rebuilt master, and Circle CI fails on master too: https://circleci.com/gh/atom/watcher/566

**Comment by smashwilson** [comment]
@jasonrudolph Looks like `clang-tidy` has gotten smarter in the time since I was last spending time on this repo. I've fixed the new problems it found in #175, so this should be able to pass now 🤞

**Comment by jasonrudolph** [comment]
Thanks, @smashwilson!


200w_d

**Pull request merged**
